version: '3'

services:
  app:  # appという名前のサービスを定義
    build: .  # Dockerファイルの場所を指定（カレントディレクトリ）
    tty: true  # コンテナを起動した状態に保つためのオプション

    # コンテナ内からterraformを利用したい場合にAWSアクセスようのアクセスキーが必要
    # 環境変数に入れておくと、terraformが環境変数から自動的に読んでくれる
    # 誤ってGitHubに公開しないように注意
    # 環境変数の追加は都度exportコマンドでも可能
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    # ホストマシンとコンテナ間でデータを共有するためのボリュームを指定
    volumes:
      - ../:/workspace

    # mydbというサービスに依存。これにより、appサービスはmydbサービスが起動した後に起動
    depends_on:
      - mydb

  # mydbという名前のサービスを定義
  mydb:
    image: mysql:8.0.20
    container_name: my-db
    
    # mysql構築時に使用する環境変数
    # コチラも秘匿情報の場合GitHubに公開注意 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
    
     # MySQLのデータを永続化するためにボリュームを使用します。
    volumes:
      - db_data:/var/lib/mysql
    
    # ポートのマッピング
    ports:
      - 3306:3306

volumes:
  db_data:
