name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "./github.workflows/back.yml"
      - "./back"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "./github.workflows/back.yml"
      - "./back"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./back"
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test